### ISSUE TITLE
Error on wpcf7_field_group_remove_button

### ISSUE THREAD

**Issue by asilvestre87** [felipeelia/cf7-repeatable-fields#1]
Hi felipeelia, 
I detect a bug when you add a filter for change remove button.
You repeat "wpcf7_field_group_remove_button" filter into class-cf7-repeatable-fields.php. 
At line 118 and 127.
I think that the first filter (line 118) shoud named "wpcf7_field_group_remove_button_atts" like the "wpcf7_field_group_add_button_atts" filter. In fact you explain this funcionality at the comments for this filter.

Regards

**Comment by felipeelia** [comment]
I've just uploaded the fix, @asilvestre87. Thanks a lot.

I've created this plugin in a hurry, hoping to get some help from others folks to make it better quickly. I'm glad to see that someone already installed it :)
