### ISSUE TITLE
how to display an incremental number with each field group

### ISSUE THREAD

**Issue by manjeetmca08** [felipeelia/cf7-repeatable-fields#10]
Want To add
Section 1

Section 2

Section 3

Section n

in the repeatable section

**Comment by robhuska** [comment]
I did this via CSS Counters

```.wpcf7-field-groups {
	counter-reset: repeatable-fields-counter;
}
.wpcf7-field-groups .wpcf7-field-group {
	counter-increment: repeatable-fields-counter;
}
.wpcf7-field-groups .wpcf7-field-group .index:after {
	content: counter(repeatable-fields-counter);
}```

Then you just need to add a `<span class="index"></span>` somewhere within your repeated group

**Comment by felipeelia** [comment]
It would be nice to have this documented somewhere. The FAQ section would be a good place for this.

**Comment by rtpHarry** [comment]
When this does get copied to the docs, make sure the dot is removed from the span:

    <span class="wpcf7-field-group-index"></span>

Not

    <span class=".wpcf7-field-group-index"></span>

**Comment by felipeelia** [comment]
We already have a JS solution [here](https://github.com/felipeelia/cf7-repeatable-fields#how-can-i-display-the-group-index-number-in-the-form) but the CSS one is cleaner. If you have the time for it, a PR would be more than welcome @rtpHarry :)

**Comment by felipeelia** [comment]
Changed in https://github.com/felipeelia/cf7-repeatable-fields/wiki/Frequently-Asked-Questions. Thanks!
