### ISSUE TITLE
Duplicate items are not selectable via jQuery.

### ISSUE THREAD

**Issue by designfor** [felipeelia/cf7-repeatable-fields#13]
In line 53 of the script.js file I would suggest changing clone () to clone (true).

var $new_group = $groups.data( 'group-model' ).clone();
to
var $new_group = $groups.data( 'group-model' ).clone(true);

**Comment by robhuska** [comment]
Anther thing that would be nice along with this is to pass `$new_group` into the triggered event.

Line 55 from this:
`$$.trigger( 'wpcf7-field-groups/added' );`

Line 55 to this:
`$$.trigger( 'wpcf7-field-groups/added', [$new_group] );`

**Comment by felipeelia** [comment]
Thank you both for the suggestions. I've finally implemented these changes with 74edb3d.
