### ISSUE TITLE
Format Date in Email template issue

### ISSUE THREAD

**Issue by janecekmato** [felipeelia/cf7-repeatable-fields#14]
Hi,
i have issue with formatting date in email. In classic field (without repeatable group) formatting date in email template working like this [_format_{field name} “{date format}”]. But when i use it under repeatable group, i am getting shortcode as result. So shortcode under repeatable group is not translated. Maybe your plugin not know it? Am i correct? If yes, how can i fix it?

Thanks

**Comment by felipeelia** [comment]
This was finally fixed with 6fcd115. Thanks for reporting!
