### ISSUE TITLE
Validation skips required fields on same line.

### ISSUE THREAD

**Issue by lesjj** [felipeelia/cf7-repeatable-fields#16]
Hey, 

I've got two required fields on the same line (house address and house number), but for some reason the validator skips one of those two fields when sending the form. The user can sent the form by only filling in one while they need to fill in both. How is this possible?

Cheers,

lesJJ

**Comment by felipeelia** [comment]
I know it's been a while but can you please provide here how you've set up the form, @lesjj ? Thanks!

**Comment by lesjj** [comment]
Hi,

Someone made it custom for me. It isn't that easy apperently. I hired someone on fiverr to do this. 
Check: hermsenme.com

Cheers,

lesJJ

**Comment by felipeelia** [comment]
Nice to know! I'll close this one right now.

Thanks
