### ISSUE TITLE
Not working on Safari or iPhone 6S

### ISSUE THREAD

**Issue by RyanChampniss** [felipeelia/cf7-repeatable-fields#17]
Hi, I'm having problems getting this plug in to work correctly on Safar, on my Mac (fine on Chrome and Firefox) and on all browsers on my iPhone. The buttons both display by default (normally, the remove button is hidden unless the group has been repeated), when clicked, neither button does anything.

The website is: 
https://www.makebelieveideas.com/new-contact-form-test-page/

Any help would be appreciated!

Ryan

**Comment by felipeelia** [comment]
Hey @RyanChampniss ! I took so much time to be back to you here that I guess you gave up on the plugin, right? Sorry for that, mate.
I'll close the issue right now but feel free to provide more info if you still have this problem. Thanks!
