### ISSUE TITLE
Can not create nested field groups

### ISSUE THREAD

**Issue by tasaduq** [felipeelia/cf7-repeatable-fields#19]
Can not create nested field groups, I was trying to do the following and it did not work.

```
[field_group chapters id="chapters-groups" tabindex:1]
   <div class="col-md-12 col-sm-12 col-xs-12" style="padding:0;">
      <label>[textarea* chaptername placeholder "Chapter name" ]   </label>
      [field_group topics id="topics-groups" tabindex:2]
      <label>[text topicname placeholder "Topic name" ]   </label>
      [/field_group]
   </div>
[/field_group]
```

**Comment by felipeelia** [comment]
Hi @tasaduq! What exactly didn't work? Please share:
1. Your website URL
2. Your Mail Tab content
3. Your Form Tab content.

Thanks.

**Comment by tasaduq** [comment]
Thank you for the prompt reply (wasn't expecting it)!

The form is not generated as expected. check the following screenshot, the one short code breaks. 
![image](https://user-images.githubusercontent.com/9743841/52339230-5be35c80-2a2e-11e9-81e0-08f14b0aba49.png)

The expected behavior was to to be able to add dynamic fields inside of a dynamic field.

Heres a link if you want to check it out https://skillupz.com/request-for-a-course/
(The change might not be there after a while. Since I need to roll this out ASAP.)

> Hi @tasaduq! What exactly didn't work? Please share:
> 
> 1. Your website URL
> 2. Your Mail Tab content
> 3. Your Form Tab content.
> 
> Thanks.

**Comment by felipeelia** [comment]
AH, now I see! You're trying to use nested repeatable fields, right? I'm sorry, the plugin wasn't designed for that, so it'll probably won't work as expected :(

**Comment by tasaduq-HL** [comment]
Yes, exactly, that is what I am trying to do.

**Comment by felipeelia** [comment]
Yeah, sorry, this plugin won't help you. I hope you can find the solution somewhere else or get the form designed in a way you don't need the nested groups (I know that can be really hard sometimes). Good luck!

**Comment by felipeelia** [comment]
Closing this one right now as I can't see nested groups as a feature in the near future.
