### ISSUE TITLE
Repeated elements grouping to one after validation fail

### ISSUE THREAD

**Issue by gergelyvizvari** [felipeelia/cf7-repeatable-fields#24]
Repeated elements grouping to one after validation fail

i'm on wordpress 5.3.
Firstly i had to manually add the wp_enqueue_scripts into my functions.php but this is totally not a problem.

The repeater fields are working almost flawless. But when i submit the form and the validation fails the groups will become one. So one repeated group with 2 field will become 4 fields in the same group

```
[field_group basic-infos id="basic-info-groups" tabindex:1]
        [text* project id:project class:form-control]
        [text* user id:user class:form-control]
[/field_group]
[submit id:submit class:btn class:btn-primary "SEND REGISTRATION"]
```

**Comment by felipeelia** [comment]
Thanks for reporting your problem @gergelyvizvari .

Can you please share your website URL so I can give a look at that?

**Comment by gergelyvizvari** [comment]
The site is not online, but if you copy the mentioned code above, and send the form with empty field you will see the result.

**Comment by felipeelia** [comment]
Sorry but I could not reproduce any of your issues, @gergelyvizvari . Using the new Twenty Twenty theme I did not need to enqueue the script again and the validation seems OK (using the markup you provided).

Did you test it without any other plugin and with a twenty* theme?
