### ISSUE TITLE
Sending Group Data to Webhooks

### ISSUE THREAD

**Issue by TiMS-Design** [felipeelia/cf7-repeatable-fields#29]
Hello, i use the repeatable fields and send the data to a Webhook.
how can i send the data from a group as JSON Object?
Can you help me?

**Comment by felipeelia** [comment]
Hi there! I'd need to understand your problem a bit better. How are you sending the data right now?

**Comment by TiMS-Design** [comment]
Hi, i have installed the add-on CF7 to Zapier, where i can send the data of the Formular to a webhook as JSON.

When is send the data to the Webhook i get the following data:
```
{
"variable 1" : "???????",
"variable 2" : "???????",
"group-variable__1": "???????",
"group-variable__2": "???????",
}
```
But i need something like this:

```
{
"variable 1" : "???????",
"variable 2" : "???????",
"group" : {"group-variable__1": "?????", "group-variable__2" : "???????"}

}

```

**Comment by felipeelia** [comment]
Thanks for the info, @TiMS-Design !

By `CF7 to Zapier` you mean [this plugin](https://wordpress.org/plugins/cf7-to-zapier/), right? If so, it seems they provide a filter which could be used to achieve what you want: `ctz_post_request_args`

It'll require some custom code in an additional plugin, though. The code below can be a start for you but keep in mind it was not tested.
```
function adjust_cf7_groups( $args ) {
  $body = $args['body'];
  $body = json_decode( $body );

  $body['group'] = [];
  $i             = 1;
  while( isset( $body["group-variable__{$i}"] ) ) {
    $body['group']["group-variable__{$i}"] = $body["group-variable__{$i}"];
    $i++;
  }

  $args['body'] = json_encode( $body );
  return $args;
}
add_filter( 'ctz_post_request_args', 'adjust_cf7_groups' );
```
