### ISSUE TITLE
BUG: Required checkbox fields

### ISSUE THREAD

**Issue by felipeelia** [felipeelia/cf7-repeatable-fields#61]
### Describe the bug

From https://wordpress.org/support/topic/compatibility-issues-with-cf7-5-7/#post-16924132

> The update appears to have mostly resolved the required field issues, although there does still appear to be one issue with required checkbox fields where submitting a form with no checkboxes filled out will throw a “One or more fields have an error.” error but doesn’t indicate which field has the problem. I was able to reproduce it on both our existing site and a fresh installation.

```
[checkbox* mycheckbox "thing1" "thing2"]
```

### Steps to Reproduce

To be investigated

### Form tab contents

To be investigated

### Mail tab contents

To be investigated

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrispink** [comment]
I am experiencing this issue with a combination of `input[type="text"]` and `textarea`

**Comment by felipeelia** [comment]
@chrispink do you mind opening a new issue with the values you are using for both the Form and Mail tabs? Thanks
