### ISSUE TITLE
Great plugin!

### ISSUE THREAD

**Issue by mattish91** [felipeelia/cf7-repeatable-fields#66]
### Describe your question

First of all i have to say im amazed with how easy this was to setup on our website!

But i do have some questions about the output to email (if possible) 

I would like to have it output in a table (if possible) in order to automate as much information as possible.

For example i have two input fields information 1 and information 2 next to each other.

Then i want a table in the email like: 

```
<th>Information1</th><th>some other information</th><th>Information2</th>
<tr>Value_information1</tr><tr>Empty_value</tr><tr>Value_information2</tr>
```

How do i do that? ^^ 

Especially if the repeatable form includes both information 1 and information 2 as both of these fields gets repetable?

Would be great if something like this gets documented in your wiki as well :) Everything else was straight forward.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @mattish91,

Thanks! It would be great if you could share those kind words in a review on WP.org: https://wordpress.org/support/plugin/cf7-repeatable-fields/reviews/#new-post :-)

Answering your question, if your group looks like this in the Form tab:
```
[field_group emails id="emails-groups" tabindex:1]
	<label>Your Email (required)[email* your-email]</label>
	[radio your-radio use_label_element default:1 "radio 1" "radio 2" "radio 3"]
	[select* your-menu include_blank "option1" "option 2"]
	[checkbox* your-checkbox "check 1" "check 2"]
[/field_group]
```

You can use something like this in the Mail tab:
```
<table>
	<tr>
		<th>#</th>
		<th>Checkbox</th>
		<th>E-mail</th>
		<th>Radio</th>
		<th>Select</th>
	</tr>
[emails]
	<tr>
		<td>[group_index]</td>
		<td>[your-checkbox]</td>
		<td>[your-email]</td>
		<td>[your-radio]</td>
		<td>[your-menu]</td>
	</tr>
[/emails]
</table>
```
